### ISSUE TITLE
Installing the Graphical Modeling plugin - Package ELK is missed 

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama.graphical.modeling#12]
Hello,
When installing the new version of Graphical Modeling plugin, it shows errors as below.
I am using the continuous build version on Windows 10 64bit.
Thank you for your times!
Best regards,
Quang

_______________________________________________________________________________________

Cannot complete the install because one or more required items could not be found.
  Software being installed: Graphical_modeling 1.7.0.201801191055 (idees.gama.feature.graphical_modeling.feature.group 1.7.0.201801191055)
  Missing requirement: ELK Layered Layout Algorithm 0.4.0.201801010901 (org.eclipse.elk.alg.layered 0.4.0.201801010901) requires 'bundle org.eclipse.elk.alg.common.compaction 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Graphical_modeling 1.7.0.201801191055 (idees.gama.feature.graphical_modeling.feature.group 1.7.0.201801191055)
    To: org.eclipse.elk.alg.layered [0.4.0.201801010901]

**Comment by ptaillandier** [comment]
It is solved (I just tested it, and it works).
