### ISSUE TITLE
Install New Software does not open on GAMA - V1.6.1 in Linux

### ISSUE THREAD

**Issue by mercedesgabriela** [gama-platform/gama.graphical.modeling#15]
I tried installing the graphical editor of the manual pag 124, and it did not let me, so i closed the app, and tried later.

When trying later, I couldn't even open the "Install New Software" option under Help Menu.

I tried deleting the latest plug-in "csvedit", and nothing changed.

Please help.

![ticket02](https://user-images.githubusercontent.com/32800567/36327777-a0834b8a-139a-11e8-9234-551f615d5424.jpg)
![ticket01](https://user-images.githubusercontent.com/32800567/36327778-a09b95b4-139a-11e8-8bf3-d2ffa88894aa.jpg)

**Comment by ptaillandier** [comment]
Hi,

I am not sure of the version of GAMA (and the documentation) that you are
using. Do you need to use GAMA 1.6?
My advice is to use the latest version of GAMA 1.7 (here
<https://github.com/gama-platform/gama/releases/tag/latest>) and to use
this documentation:
https://github.com/gama-platform/gama/wiki/G__GraphicalEditor

Cheers,

Patrick

2018-02-16 21:31 GMT+01:00 mercedesgabriela <notifications@github.com>:

**Comment by mercedesgabriela** [comment]
Hi, well I installed GAMA 1.6 because a colleague told me that version 1.7 is still not oficial and still goes through a lot of inestability. Do you use 1.7? Have you experienced any problems?

**Comment by tcquang** [comment]
Hi mercedesgabriela,
I think GAMA 1.7 is better than the version 1.6.1.  The software can be updated easily. 
I am also using Graphical Modeling plugin with GAMA 1.7. This plugin now works very well because the issues on version 1.6.1 are well fixed. 
Cheers,
Quang
