### ISSUE TITLE
GM plugin: Automatically inserted a blank line at the begin of actions

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama.graphical.modeling#18]
Dear Patrick,
In the diagram mode, when opening the actions (or reflexes) for editing,  it automatically inserted a blank line at the begin of actions.
There is the same behavior with agents but it added blank lines to the init area.
In the figure attached, I have opened an action for 10 times, there are thus 10 blank lines added. 
Thank you for reading!
Best regard,
Quang
![auto_insert_blank lines](https://user-images.githubusercontent.com/11825516/39402251-48259214-4b84-11e8-91df-04fa5e42d8cd.JPG)

**Comment by ptaillandier** [comment]
It seems to be fixed
