### ISSUE TITLE
GM plugin: Cannot generate gaml model from diagram

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama.graphical.modeling#19]
Dear Patrick,
I have issue to generate gaml model from diagrams.
It shown the error "Input doesn't exist"
I am using GAMA 1.8 continuously built with an installed GM plugin. The OS  is Windows 10 64b, java 1.8.181 64b.
Thank you for watching 
Best regards,

Quang

**Comment by tcquang** [comment]
I would like to update the error log as in the picture.

![generate gaml code](https://user-images.githubusercontent.com/11825516/46117670-bcff5600-c22c-11e8-86a0-e7365e0eefe3.PNG)

**Comment by tcquang** [comment]
Hello,

When I close GAMA, then open GAMA and diagrams again. It works. The diagrams seem to be not saved before closing GAMA.

Best regards,

Quang

**Comment by tcquang** [comment]
Hello, 
I was wondering if there is any update for this function because we need this function for debugging diagrams.
Thank you very much in advance for your times.
Best regards,
Quang

**Comment by ptaillandier** [comment]
Hi Quang,

Unfortunately, I do not have the time right now to fix it, but I plan to do
it for the end of this month

Patrick

**Comment by tcquang** [comment]
Thank you in advance!

Best regards,

Quang
