### ISSUE TITLE
Trying to install on GAMA 1.8

### ISSUE THREAD

**Issue by ghost** [gama-platform/gama.graphical.modeling#25]
Hey, 
I am very very new to GAMA (and Github) but I want to implement it for my master thesis. 
I read about the graphical modeler and it sounds like a good start. 
Unfortunately, I can't get it to run, is it still compatible with the latest GAMA version? 

![grafik](https://user-images.githubusercontent.com/59507797/79445513-167cd080-7fdd-11ea-9999-608ea9d5934e.png)

this warning appears, after installing anyway the graphical modeler is not available: 
I tried installing it another thime, then it asks if I want to update certain parts to be compatible

After doing so and restarting, an error appears while starting 

I`d be very thankful for any help 

Best
Max

**Comment by ptaillandier** [comment]
Hi,

It seems to work fine on my computer. You can test to install this
extension with the latest version of GAMA (daily built) :
https://github.com/gama-platform/gama/releases/tag/continuous

Cheers,

Patrick

**Comment by ghost** [comment]
Hi Patrick, 
that worked, thanks!
