### ISSUE TITLE
Graphical Modeling: errors with a shape_file type

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama.graphical.modeling#3]
Dear Patrick,
I know that the plug-in is developing, but I found many new interesting things in the GM plug-in (BDI through the interface...), so I would like to test it.
However, there is an error when declaring a shape file type as in the following figure.
Besides that, when generate Gaml code, there are a lot of blank lines in the init block and in the agent.
Thank you for this work!
Cheers

![blank lines](https://cloud.githubusercontent.com/assets/11825516/15867415/685f3db0-2d0d-11e6-938f-a053e7757ba6.JPG)
![shap_file_type_error](https://cloud.githubusercontent.com/assets/11825516/15867416/6862f2ac-2d0d-11e6-86d7-dea98ea00a06.JPG)

**Comment by ptaillandier** [comment]
should be fixed (I just remove _file type from available types)
