### ISSUE TITLE
The installation guide for the Graphical Modeling plug-in

### ISSUE THREAD

**Issue by tcquang** [gama-platform/gama.graphical.modeling#4]
Dear Mr. Taillandier,
I am looking for the guide to install the Graphical Modeling (GM) plugin, I remember that it was in the Wiki of GAMA, but I could not find it. 
I am installing a GIT version of GAMA (win 32) for exporting the GAMA 32bit  version with the GM plugin. Could you please tell me the packages that I need to install to eclipse for the GM plugin.
Thank you very much for you help and you time!
Best regards,
Quang

**Comment by reyman** [comment]
I think you can use the classic plugin installation way by adding this url, which contain the latest GM plugin : http://vps226121.ovh.net/gamamodeling

**Comment by tcquang** [comment]
Dear Reyman,
I have installed the GM plugin. It works fine with the version git a5e037f34. 
There are two plugins that we need to install for eclipse: 
- Graphiti 0.13 : http://download.eclipse.org/graphiti/updates/0.13.0
- Eclipse Layout Kernel: http://download.eclipse.org/elk/updates/releases/0.1.0/
  Thank you very much !

**Comment by ptaillandier** [comment]
done (in the wiki)
